package palette_test

import (
	"fmt"
	"image/color"
	"math"
	"sort"
	"strings"
	"testing"

	"github.com/sebdah/goldie/v2"

	"github.com/jv-k/gh-runs/v2/internal/palette"
)

// The floors, from settings R22. They live here rather than in the package because they are
// the assertion, not a value the product paints with: the product needs the reference
// backgrounds, and nothing in it needs to know what ratio they were chosen to clear.
const (
	roleFloor      = 4.5  // WCAG 2.x AA for normal text
	highlightDelta = 10.0 // CIE76 ΔE, so a highlight is discernible from the background at all
)

// TestEveryRoleClearsTheContrastFloor is settings R22 for Roles, and half of AC15. It walks
// Roles() rather than a list written here, so a role added later is covered by existing to be
// returned, which is what the accessor's doc comment promises.
//
// The floor is measured against the appearance's reference background rather than against
// black and white. ADR-0024 has the argument: contrast to a dark foreground rises
// monotonically as the background lightens, so clearing #faf4f2 clears every lighter
// background by construction, and measuring the dark set against #2d2a2e rather than #000000
// is what put dark Muted in scope at 4.10.
func TestEveryRoleClearsTheContrastFloor(t *testing.T) {
	for _, a := range []palette.Appearance{palette.Dark, palette.Light} {
		bg := reference(t, a)
		for _, name := range sortedRoles() {
			role := palette.Roles()[name]
			if got := contrastRatio(resolve(t, role, a), bg); got < roleFloor {
				t.Errorf("%s role %s is %.2f:1 against the %s reference background %s, want %.1f:1 or better (R22)",
					a, name, got, a, referenceHex(a), roleFloor)
			}
		}
	}
}

// TestEveryHighlightClearsBothFloors is settings R22 for Highlights, and AC15's other half. A
// Highlight carries two obligations its two halves would not carry apart: its own foreground
// must be legible on its own background, and its background must differ from the terminal's
// or there is no highlight to see.
//
// The second floor is stated in CIE76 ΔE rather than in a luminance ratio because a luminance
// ratio gives an answer that contradicts the eye here. Match light #ffff87 is 1.03 against
// #faf4f2 and unmissable in fact, and a luminance floor would have forced the search
// highlight dark to satisfy a number (ADR-0024).
func TestEveryHighlightClearsBothFloors(t *testing.T) {
	for _, a := range []palette.Appearance{palette.Dark, palette.Light} {
		bg := reference(t, a)
		for _, name := range sortedHighlights() {
			h := palette.Highlights()[name]
			fg, hbg := resolve(t, h.Foreground(), a), resolve(t, h.Background(), a)

			if got := contrastRatio(fg, hbg); got < roleFloor {
				t.Errorf("%s highlight %s is %.2f:1 between its own foreground and background, want %.1f:1 or better (R22)",
					a, name, got, roleFloor)
			}
			if got := deltaE76(hbg, bg); got < highlightDelta {
				t.Errorf("%s highlight %s has background ΔE %.1f from the %s reference background %s, want %.1f or more: below this the highlight is not discernible at all (R22)",
					a, name, got, a, referenceHex(a), highlightDelta)
			}
		}
	}
}

// TestNoHighlightIsAlsoARole pins the split R22 draws. Roles() returns foregrounds only, so a
// Highlight appearing in both would be measured against the terminal background as though it
// were text, which is the reading that let a search match paint at 1.95:1.
func TestNoHighlightIsAlsoARole(t *testing.T) {
	roles := palette.Roles()
	for name := range palette.Highlights() {
		if _, ok := roles[name]; ok {
			t.Errorf("%s is returned by both Roles() and Highlights(); a Highlight is one thing, not two Roles (CONTEXT.md)", name)
		}
	}
}

// TestMeasuredRatiosGolden is AC15's requirement that the figures this canon quotes be
// generated by the same arithmetic that enforces them, never typed. A comment beside a value
// drifts from it; this file cannot, because it is written by the measurement.
//
// It asserts over values rather than over rendered output, so unlike the view goldens it needs
// no colour profile and no frame (settings R22's note under AC15).
func TestMeasuredRatiosGolden(t *testing.T) {
	var b strings.Builder
	b.WriteString("Measured against the reference backgrounds settings R22 names.\n")
	b.WriteString("Generated by TestMeasuredRatiosGolden. Do not edit by hand.\n\n")

	for _, a := range []palette.Appearance{palette.Dark, palette.Light} {
		fmt.Fprintf(&b, "== %s appearance, reference background %s ==\n\n", a, referenceHex(a))
		bg := reference(t, a)

		b.WriteString("Roles, WCAG 2.x contrast against the reference background:\n")
		for _, name := range sortedRoles() {
			c := resolve(t, palette.Roles()[name], a)
			fmt.Fprintf(&b, "  %-10s %s  %5.2f:1\n", name, hex(c), contrastRatio(c, bg))
		}

		b.WriteString("\nHighlights, WCAG 2.x between the pair, CIE76 ΔE of the background to the reference:\n")
		for _, name := range sortedHighlights() {
			h := palette.Highlights()[name]
			fg, hbg := resolve(t, h.Foreground(), a), resolve(t, h.Background(), a)
			fmt.Fprintf(&b, "  %-10s fg %s on bg %s  %5.2f:1  ΔE %5.1f\n",
				name, hex(fg), hex(hbg), contrastRatio(fg, hbg), deltaE76(hbg, bg))
		}
		b.WriteString("\n")
	}

	goldie.New(t).Assert(t, "measured_ratios", []byte(b.String()))
}

// resolve reads a role's concrete colour in one appearance. Colour resolves against the
// ambient appearance as it renders, which is the mechanism the theme reaches every view by,
// so reading one value means selecting the appearance around it. Use returns the restore, so
// no test leaves the ambient appearance moved.
func resolve(t *testing.T, c palette.Colour, a palette.Appearance) color.Color {
	t.Helper()
	restore := palette.Use(a)
	defer restore()
	r, g, bl, _ := c.RGBA()
	return color.RGBA{R: uint8(r >> 8), G: uint8(g >> 8), B: uint8(bl >> 8), A: 0xff}
}

// reference is the appearance's reference background as a colour.
func reference(t *testing.T, a palette.Appearance) color.Color {
	t.Helper()
	c, err := parseHex(referenceHex(a))
	if err != nil {
		t.Fatalf("reference background %s does not parse: %v", referenceHex(a), err)
	}
	return c
}

// referenceHex is the appearance's reference background as the canon writes it. The constants
// are exported from palette so R22's numbers exist in code rather than only in prose, and so
// this test reads the same values the ADR names rather than a copy of them.
func referenceHex(a palette.Appearance) string {
	if a == palette.Light {
		return palette.ReferenceBackgroundLight
	}
	return palette.ReferenceBackgroundDark
}

func sortedRoles() []string { return sortedKeys(palette.Roles()) }
func sortedHighlights() []string {
	names := make([]string, 0, len(palette.Highlights()))
	for name := range palette.Highlights() {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// sortedKeys orders a role map, so a failure names them predictably and the golden is stable.
func sortedKeys(m map[string]palette.Colour) []string {
	names := make([]string, 0, len(m))
	for name := range m {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func parseHex(s string) (color.Color, error) {
	var r, g, b uint8
	if _, err := fmt.Sscanf(strings.TrimPrefix(s, "#"), "%02x%02x%02x", &r, &g, &b); err != nil {
		return nil, err
	}
	return color.RGBA{R: r, G: g, B: b, A: 0xff}, nil
}

func hex(c color.Color) string {
	r, g, b, _ := c.RGBA()
	return fmt.Sprintf("#%02x%02x%02x", r>>8, g>>8, b>>8)
}

// rgb8 pulls the three 8-bit channels out of any color.Color. Every colour here is opaque, so
// the alpha-premultiplied form RGBA returns is the plain one.
func rgb8(c color.Color) (float64, float64, float64) {
	r, g, b, _ := c.RGBA()
	return float64(r >> 8), float64(g >> 8), float64(b >> 8)
}

// relativeLuminance is WCAG 2.x, the fifteen lines of arithmetic ADR-0024 chose over APCA
// precisely because a reader can check it against any contrast tool they already have.
func relativeLuminance(c color.Color) float64 {
	r, g, b := rgb8(c)
	lin := func(v float64) float64 {
		v /= 255
		if v <= 0.03928 {
			return v / 12.92
		}
		return math.Pow((v+0.055)/1.055, 2.4)
	}
	return 0.2126*lin(r) + 0.7152*lin(g) + 0.0722*lin(b)
}

// contrastRatio is WCAG 2.x's (L1+0.05)/(L2+0.05), lighter over darker.
func contrastRatio(a, b color.Color) float64 {
	la, lb := relativeLuminance(a), relativeLuminance(b)
	if la < lb {
		la, lb = lb, la
	}
	return (la + 0.05) / (lb + 0.05)
}

// deltaE76 is the CIE76 colour difference, a plain Euclidean distance in CIE L*a*b*. It was
// chosen over CIEDE2000 for the reason WCAG 2.x was chosen over APCA: it is short, it is
// checkable, and its extra accuracy buys nothing at a threshold as coarse as 10 (ADR-0024).
func deltaE76(a, b color.Color) float64 {
	l1, a1, b1 := toLab(a)
	l2, a2, b2 := toLab(b)
	return math.Sqrt((l1-l2)*(l1-l2) + (a1-a2)*(a1-a2) + (b1-b2)*(b1-b2))
}

// toLab converts sRGB to CIE L*a*b* through XYZ, on the D65 white point.
func toLab(c color.Color) (l, a, bb float64) {
	r8, g8, b8 := rgb8(c)
	lin := func(v float64) float64 {
		v /= 255
		if v <= 0.04045 {
			return v / 12.92
		}
		return math.Pow((v+0.055)/1.055, 2.4)
	}
	r, g, b := lin(r8), lin(g8), lin(b8)

	x := (0.4124564*r + 0.3575761*g + 0.1804375*b) / 0.95047
	y := 0.2126729*r + 0.7151522*g + 0.0721750*b
	z := (0.0193339*r + 0.1191920*g + 0.9503041*b) / 1.08883

	f := func(t float64) float64 {
		if t > 216.0/24389.0 {
			return math.Cbrt(t)
		}
		return (24389.0/27.0*t + 16) / 116
	}
	fx, fy, fz := f(x), f(y), f(z)
	return 116*fy - 16, 500 * (fx - fy), 200 * (fy - fz)
}
